---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
m <- matrix(1:9,3,3,byrow=TRUE)
m[1,]
m[,2]
m[-c(1:3),]
m[,-c(1:2)]
```

```{r}
install.packages('MASS')
library(MASS)
data("Insurance")
```

```{r}
head(Insurance)
```

```{r}
first5rows <- Insurance[1:5,]
first2cols <- Insurance[,1:2]
first2cols
Allbutrow7 <- Insurance[-7,]
Allbutrow7
Allbutcoll1_2 <- Insurance[,-c(1:2)]
Allbutcoll1_2
```


```{r}
#install.packages("ISLR")
library(ISLR)
data("Auto")
str(Auto)

```

```{r}
Auto[,'name'] <- as.character(Auto[,'name'])
class(Auto$name)
Auto[,9] <- as.character(Auto[,9])

```

```{r}
#install.packages('dplyr')
library(dplyr)
summary(Auto)
summarize(Auto, avg = mean(mpg))
```


```{r}
Auto2 <- read.csv('data/Auto.csv')
class(Auto2$horsepower)
question <- filter(Auto2, horsepower == '?')
Auto2[,4] <- as.numeric(Auto2[,4])
class(Auto2$horsepower)
```

```{r}
newdata <- select(Auto2,mpg, cylinders, displacement)
newdata
```

```{r}
secondhalf <- select(Auto2, 4:6)
secondhalf
```

```{r}
mergedata <- cbind(newdata,secondhalf)

```

